### ISSUE TITLE
in_array() expects parameter 2 to be array, object given

### ISSUE THREAD

**Issue by LarryEitel** [cviebrock/eloquent-sluggable#149] opened 2015-06-10 00:17 UTC
To resolve this (sporadic) error, I hacked SluggableTrait.php line 137

Changed `!in_array($slug, $list)` to `!in_array($slug, (array)$list)`

Error

	in_array() expects parameter 2 to be array, object given
	/home/vagrant/Code/x/vendor/cviebrock/eloquent-sluggable/src/SluggableTrait.php:137
	/home/vagrant/Code/x/vendor/cviebrock/eloquent-sluggable/src/SluggableTrait.php:214
	/home/vagrant/Code/x/vendor/cviebrock/eloquent-sluggable/src/SluggableServiceProvider.php:57
	/home/vagrant/Code/x/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:220
	/home/vagrant/Code/x/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:163
	/home/vagrant/Code/x/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1636
	/home/vagrant/Code/x/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1442
	/home/vagrant/Code/x/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:527
	/home/vagrant/Code/x/database/seeds/PlacesSeeder.php:51
	/home/vagrant/Code/x/tests/seeders/PlacesSeederTest.php:17

**Comment by Keoghan** [comment] 2015-06-10 21:37
HI Larry - was this while using Laravel 5.1?

**Comment by LarryEitel** [comment] 2015-06-10 21:50
Yes, I should have mentioned that. My tests were all passing, including those involving your package until I upgraded to 5.1.

**Comment by Keoghan** [comment] 2015-06-10 22:07
Cool, thanks - that means a fix is on the way as it's caused by the eloquent model `lists()` function returning a Collection instead of an array in 5.1.

**Comment by LarryEitel** [comment] 2015-06-10 22:08
Awesome! Thanks for the quick response. :)

**Comment by cviebrock** [comment] 2015-07-02 14:23
Fix was put in place a while ago, so closing this out.  Re-open if you see those errors again, @LarryEitel !

**Closed by cviebrock** 2015-07-02 14:23 UTC
