### ISSUE TITLE
Make Arabic characters sluggable

### ISSUE THREAD

**Issue by HassanKrayem** [cviebrock/eloquent-sluggable#419] opened 2018-03-19 15:58 UTC
Please be sure you include all the relevant information in your issue so we can help you:

- [ ] steps taken to reproduce your issue
- [ ] your configuration file(s), where relevant
- [ ] a copy of your Models that use or extend this package (just the relevant parts!)
- [ ] any other code we might need to help

Please use a descriptive title for your issue.  "Why doesn't this work?" doesn't provide 
other users much information if they are scanning the list of issues.

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by cviebrock** [comment] 2018-03-20 01:34
Duplicate of #338

**Closed by cviebrock** 2018-03-20 01:34 UTC
