### ISSUE TITLE
Not creating slug on several modules

### ISSUE THREAD

**Issue by nobreferreira** [cviebrock/eloquent-sluggable#440] opened 2018-09-20 14:40 UTC
I'm using `"laravel/framework": "5.6.*"` and `"cviebrock/eloquent-sluggable": "^4.5"`.

The app has several modules and only one has the slug correctly generated.
Next there's the code from a module that doesn't generate the slug. 
It's pretty basic. Am I missing something? Can you help me?

**Lab Model**

```
namespace Saci\Labs;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;

class Lab extends Model 
{
    protected $table    = 'labs';

    protected $fillable = array('type_id', 'name', 'slug', 'description', 'coordinator_id', 'url', 'additional_info', 'image');
    protected $visible  = array('type_id', 'name', 'slug', 'description', 'coordinator_id', 'url', 'additional_info', 'image');

    public $timestamps  = true;

    use Sluggable;

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name',
            ]
        ];
    }

```

**Labs Controller Method**
```
public function store(LabRequest $request)
{
    $lab = $this->lab->create($request->all());
    return redirect()->route('admin.labs.show', $lab)->with('success', trans('base::messages.create-success'));
}
```

**Comment by cviebrock** [comment] 2018-09-21 14:30
Offhand, I can't see why that isn't working.  Is the slug actually being generated and saved in the database?

Maybe the `create` method isn't firing the event required by the package to do the slugging.  Try adding this line in the middle of your code:

```php
public function store(LabRequest $request)
{
    $lab = $this->lab->create($request->all());
    $lab->save();  // ADD THIS
    return redirect()->route('admin.labs.show', $lab)->with('success', trans('base::messages.create-success'));
}
```

**Comment by nobreferreira** [comment] 2018-09-21 14:42
The `$lab->save();` made nothing different.

We got several modules using eloquent-sluggable and only one is working correctly and saving the slug to the DB.
The code is plain simple and I can't really find explanation to this. Maybe I'm going round in circles and in need for some distance to solve this.

**Comment by BozidarBG** [comment] 2018-09-25 16:36
i had the problem when slug was creating same slugs. like:
1. some-title
2. some-title-1
3. some-title-1 (again and again)

i fixed it by adding 'unique'=>true
return [
            'slug' => [
                'source' => 'title',
                'unique'=>true
            ]
        ];

**Comment by ielhag** [comment] 2018-10-21 06:52
I am having the same issue as @nobreferreira, tried @BozidarBG solution and it didn't work, any suggestions ?

**Comment by jam1e** [comment] 2018-10-22 10:17
I am also having this same issue.
It seems to be working on all my models that have the source set to the title, but not on the one that is set to name. I'm not sure if this is a coincidence, or if it's related to the issue.

@nobreferreira I noticed in your example you also have the source set to name. Do you experience issues where the source of a model is set to the title? Just wondering if there's a pattern here.

**Comment by bradley-varol** [comment] 2018-11-04 21:00
For me, slugs are being created when creating the model but not being updated when saving the model (in controller update method, for example).

**Comment by cviebrock** [comment] 2018-11-20 03:38
@bradley-varol Unless you have `'update' => true` in your sluggable config, the slugs won't be changed when the model is updated.  This is the intended behaviour.

@nobreferreira and @jam1e ... I'm sorry for not responding quickly.  I honestly don't see why the package would work for one model and not for another.  Could it be you have specified a `source` in the main configuration file `app/config/sluggable.php` file?  Those values *should* be overwritten by model-level configs, but maybe that's not the case?

**Comment by cviebrock** [comment] 2018-12-18 02:43
Closing due to no follow-up response.  Feel free to re-open or comment if you are still having issues.

**Closed by cviebrock** 2018-12-18 02:43 UTC
