### ISSUE TITLE
findBySlug

### ISSUE THREAD

**Issue by cernicc** [cviebrock/eloquent-sluggable#141] opened 2015-05-19 21:47 UTC
If item does not exists findBySlug returns Builder object. I think it should returned null.

I am using it in RouteServiceProvider. Tried it in Controller too. Same result.

**Comment by cviebrock** [comment] 2015-05-20 03:44
I'm not sure how that would be the case.  The current code has:

```php
	public function scopeWhereSlug($scope,$slug)
	{
		$config = $this->getSluggableConfig();
		return $scope->where($config['save_to'],$slug);
	}

	public function scopeFindBySlug($scope,$slug)
	{
		return $scope->whereSlug($slug)->first();
	}
```

So, `Model::findBySlug('foo')` should return the first record or null.  Can you show some code that fails? Even better, make a PR with a failing test?

**Comment by Keoghan** [comment] 2015-05-20 12:26
Hi - I wrote a small test which I'm happy to share. I think it's caused by the findBySlug being called as a scope - Eloquent appears to return the current Builder when a scope returns falsey(sp?).  

```php 
$scope->whereSlug($slug)->first();
``` returns `null`

but then \Eloquent\Builder::callScope returns a Builder.

**Comment by cviebrock** [comment] 2015-05-20 12:35
You're probably right.  `findBySlug` shouldn't be a scope since it returns an Eloquent object or null, never a chainable Builder query.

@xire28 do you agree (you made the original PR with this, I believe)?

**Comment by xire28** [comment] 2015-05-20 14:04
Based on Eloquent poorly documented API, [`first`](http://laravel.com/api/4.1/Illuminate/Database/Eloquent/Builder.html#method_first) returns `Model` | `builder` | `null`. It's not explain when it returns `null`, I thought it was when not record was found but it's apparently not correct when called as scope.

If you define `findBySlug` as a class method, you will not be able to handle `withTrashed` scope of `softdelete`.

**Comment by xire28** [comment] 2015-05-20 16:12
Usages of `findBySlug`:
- Static call : `Model::findBySlug($slug)` returns `Model` or `null` if model not found
- Scope call : `Model::withTrashed()->findBySlug($slug)->get()` returns `Model` or `null` if model not found

A scope's role is to reduce the search perimeter (where clause), not to return one or multiple records directly.

**Comment by xire28** [comment] 2015-05-20 17:28
I agree

**Comment by cviebrock** [comment] 2015-07-02 14:25
Closing, since @Keoghan's fix should've taken care of this.

**Closed by cviebrock** 2015-07-02 14:25 UTC
